version: '3.7'

services:
  tp3:
    image: red-panda-producer
    depends_on:
      - redpanda
    ports:
      - 80:80
    networks:
      - monreseau
  redpanda:
    image: vectorized/redpanda:latest
    ports:
      - "9092:9092" # Port pour le broker Kafka
      - "9644:9644" # Port pour les métriques RedPanda
    volumes:
      - /path/to/redpanda/data:/var/lib/redpanda/data # Volume pour stocker les données
    command: redpanda start --overprovisioned --smp 1 --memory 1G # Commande pour démarrer RedPanda
    networks:
      - monreseau

networks:
  monreseau: